// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0xfdPa2cHZfY2hlJRdBXSXeb4_2rz9yg',
    appId: '1:455957241370:web:4ad4857d33de633cf13ba3',
    messagingSenderId: '455957241370',
    projectId: 'quizauth-6349d',
    authDomain: 'quizauth-6349d.firebaseapp.com',
    storageBucket: 'quizauth-6349d.firebasestorage.app',
    measurementId: 'G-VVK905F491',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoaQcWfdBvJYv4K5hRI-ZLFUIeGZdovLk',
    appId: '1:455957241370:android:3d06de189466aaccf13ba3',
    messagingSenderId: '455957241370',
    projectId: 'quizauth-6349d',
    storageBucket: 'quizauth-6349d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3BOmMmP3QaCxcj45V8NW5rbKrQR3VuAM',
    appId: '1:455957241370:ios:790241c67d5b4166f13ba3',
    messagingSenderId: '455957241370',
    projectId: 'quizauth-6349d',
    storageBucket: 'quizauth-6349d.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3BOmMmP3QaCxcj45V8NW5rbKrQR3VuAM',
    appId: '1:455957241370:ios:790241c67d5b4166f13ba3',
    messagingSenderId: '455957241370',
    projectId: 'quizauth-6349d',
    storageBucket: 'quizauth-6349d.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0xfdPa2cHZfY2hlJRdBXSXeb4_2rz9yg',
    appId: '1:455957241370:web:a13d0d8523389786f13ba3',
    messagingSenderId: '455957241370',
    projectId: 'quizauth-6349d',
    authDomain: 'quizauth-6349d.firebaseapp.com',
    storageBucket: 'quizauth-6349d.firebasestorage.app',
    measurementId: 'G-83XFD53DTG',
  );
}
